# encoding: utf-8
---
recipe:
  Rx: config
  args:
    - schema
  description: >-
    Append the bilingual hint filter, switch, and settings to one schema.

install_files: >-
  integrations/*/integration.yaml

patch_files:
  ${schema}.custom.yaml:
    - integrations/${schema}/integration:/patch