# encoding: utf-8
---
recipe:
  Rx: config
  args:
    - schema=rime_ice
  description: >-
    Append the bilingual hint filter, switch, and settings to one schema.

install_files: >-
  integrations/*/integration.yaml

patch_files:
  ${schema:-rime_ice}.custom.yaml:
    - integrations/${schema:-rime_ice}/integration:/patch